### ISSUE TITLE
Please consider renaming this to grafana-azure-sdk-go or grafana-azure-wrapper-go

### ISSUE THREAD

**Issue by mitulmk** [grafana/grafana-azure-sdk-go#1]
For example, to avoid confusion with https://github.com/Azure/azure-sdk-for-go

**Comment by andresmgot** [comment]
I like `grafana-azure-sdk-go`, let me try renaming this repository.

**Comment by andresmgot** [comment]
Done! cc/ @kostrse (in case you already have some work in progress related to this repository).
