### ISSUE TITLE
Configurable Azure authentication middleware for support of custom token providers

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana-azure-sdk-go#16]
Add support for parametrization into the Azure authentication middleware to support custom token providers which are not directly implemented in the SDK.

**Comment by andresmgot** [comment]
Can you elaborate on this issue @kostrse ? An example would be nice

**Comment by kostrse** [comment]
Currently `AzureMiddleware` implemented to call AzureTokenService and there's no way to customize this behavior. We're getting into a situation when different datasources may support different authentication types. ADX supports OBO which other datasources do not support etc.

So it would be great to be able to pass configuration to the AzureMIddleware during initialization to override it's behavior

e.g. [here](https://github.com/grafana/grafana/blob/9512f1e1af8fa1d7742e8058db8953d60e6399d1/pkg/tsdb/prometheus/azureauth/azure.go#L50)

```go
azhttpclient.AddAzureAuthentication(opts, { a custom list of token providers }, credentials, scopes)
```

To make [this](https://github.com/grafana/grafana-azure-sdk-go/blob/286705c3e737a92fd3e9a411ed70bc592f335855/azhttpclient/middleware.go#L17) code block configurable.
